export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const MY_ORDER_LIST_REQUEST = 'MY_ORDER_LIST_REQUEST'
export const MY_ORDER_LIST_SUCCESS = 'MY_ORDER_LIST_SUCCESS'
export const MY_ORDER_LIST_FAIL = 'MY_ORDER_LIST_FAIL'

export const PRICE_CURRENCY_REQUEST = 'PRICE_CURRENCY_REQUEST'
export const PRICE_CURRENCY_SUCCESS = 'PRICE_CURRENCY_SUCCESS'
export const PRICE_CURRENCY_FAIL = 'PRICE_CURRENCY_FAIL'

export const PRICE_TO_ZERO = 'PRICE_TO_ZERO'
